name: Composercat
description: 'Graphical User Interface for the Composer package manager (PHP)'
website: 'https://getcomposercat.com'
keywords:
  - php
  - composer
  - programming
  - productivity
category: 'Developer Tools'
license: COMMERCIAL
