name: 'ProDoctor Medicamentos'
description: 'Look up medicines, read their patient and healthcare professional leaflets, find out generic and similar alternatives available in Brazil.'
website: 'https://prodoctor.net/medicamentos'
keywords:
    - 'ProDoctor Software'
    - 'Drugs Instruction Leaflet'
    - 'Medicine'
    