name: Stack
description: 'Tweetdeck for all your social apps'
website: 'https://stackapp.download/'
category: 'Social Networking'
keywords:
  - mac
  - facebook
  - twitter
  - instagram
  - social
  - tweetdeck
