name: WorktreeX
description: WorktreeX is a desktop application built to provide interactive visualizations and automations for excel spreadsheet links and workflows.
website: https://www.kleverin.com
repo: https://github.com/KleverinLTD/WorktreeX
keywords:
  - Workflow
  - Link manager
  - Spreadsheet
category: Productivity
