name: 'Check Semantic Commit'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}
jobs:
  main:
    permissions:
      pull-requests: read # to analyze PRs (amannn/action-semantic-pull-request)
      statuses: write # to mark status of analyzed PR (amannn/action-semantic-pull-request)

    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
